---
title: "P8105 Homework 5"
author: "sarah_8105"
output: github_document
---


This is my fifth homework assignment for P8105.

```{r libraries}
library(tidyverse)
library(rvest)
library(readr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 2


```{r p2_import}
p2_df = tibble(file_name = list.files(path = "./data/"))

import_csv = function(file) {
  read_csv(file) %>%
  janitor::clean_names() %>%
    pivot_longer(
      week_1:week_8,
      names_to = "week",
      names_prefix = "week",
      values_to = "observation"
    )
}

p2_df = p2_df %>%
  mutate(
    study_arm = ifelse(str_detect(file_name, "con"), "Control", "Experimental"),
    study_id = str_sub(file_name, 5, 6),
    data = map(str_c('./data/',file_name), import_csv)
    )

```